;--------------------------------------------------------------------------------
; winPenPack Project § X-Software collection
; Copyright © 2005-2018 Danilo Leggieri and winPenPack Development Team
; X-Launcher 1.5.4 Copyright © Gabriele Tittonel and winPenPack Development Team
;
; Web: http://www.winpenpack.com/
; E-mail: winpenpack@gmail.com
;
; Released under the terms and conditions of the winPenPack License Agreement 
; (see license.txt or http://www.winpenpack.com/main/page.php?5)
;--------------------------------------------------------------------------------
[Version]
Software=Supremo Remote Control
Soft.Author=Nanosystems
Launcher=1.5.4
Ini Author=Gabriele Tittonel
Ini Revision=1
Ini Rev.Author=Daniele Lolli feat. Claude
Ini Date=16-03-2026

[Setup]
AppName=Supremo

[FileToRun]
PathToExe=$Bin$\$AppName$\Supremo.exe
Parameters=/portable

[RunBefore]
SetWorkingDir=$Bin$\$AppName$

[Options]
DeleteTemp=true
ShowSplash=false
ShowTrayTip=false
WriteLog=false
FirstRun=false
RunWait=false